// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/donors/Compact.tsx": () => import("../components/mockups/donors/Compact.tsx"),
  "./components/mockups/donors/Fintech.tsx": () => import("../components/mockups/donors/Fintech.tsx"),
  "./components/mockups/donors/Social.tsx": () => import("../components/mockups/donors/Social.tsx")
};
